version: "3.3"
services:
  parseable:
    image: containers.parseable.com/parseable/parseable:latest
    restart: always
    ports:
      - 172.17.0.1:50633:8000
    env_file:
      - .env
    volumes:
      - ./parseable/staging:/parseable/staging
      - ./parseable/data:/parseable/data
    command: parseable local-store
