version: "3.3"
services:
  minio:
    image: elestio/minio:latest
    restart: always
    command: server /data
    ports:
      - "172.17.0.1:27918:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./parseable/s3_data:/data
  # This service just makes sure a bucket with the right policies is created
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb minio/parseable;
      /usr/bin/mc anonymous set public minio/parseable/public;
      exit 0;
      "

  parseable:
    image: containers.parseable.com/parseable/parseable:latest
    restart: always
    ports:
      - 172.17.0.1:50633:8000
    env_file:
      - .env
    volumes:
      - ./parseable/staging:/parseable/staging
      - ./parseable/data:/parseable/data
    command: parseable s3-store
